### ISSUE TITLE
Where is "./configure"?

### ISSUE THREAD

**Issue by rujiel** [erlkonig/alienfx#10]
I know I'm a bit late to the party on asking this, but the instructions say to run "./configure", but this file isn't in the zip, there's just ./configure.ac. 

Also does this tool rely on python 2 being installed?
Thank you

**Comment by FireBurn** [comment]
Running autoconf should create it

**Comment by rujiel** [comment]
Thank you!

**Comment by FireBurn** [comment]
I'm not sure how active this project is any more, but it might be worth submitting a pull request to update the readme
